version: "3.8"

services:
  database:
    image: postgres:14
    container_name: ${POSTGRES_HOST}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    container_name: node_backend
    ports:
      - "${NODE_PORT}:${NODE_PORT}"
    depends_on:
      - database
    environment:
      NODE_ENV: ${NODE_ENV}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      NODE_PORT: ${NODE_PORT}
      VUE_PORT: ${VUE_PORT}
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/dist
    
  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: ${VITE_API_URL}
    container_name: vue_frontend
    ports:
      - "${VUE_PORT}:80"
    depends_on:
      - backend
    volumes:
      - /usr/share/nginx/html

volumes:
  pg_data:
